{% set name = "types-Werkzeug" %}
{% set version = "1.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-Werkzeug-{{ version }}.tar.gz
  sha256: 310f06032b71c28c7ae2b189b44d52c29e1a667e87c2e9e8405761b01cb83859

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/werkzeug-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for Werkzeug
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
